builds:
  - id: k3ai-cli
    binary: k3ai-cli
    main: ./
    ldflags:
      - -X github.com/kf5i/k3ai-core/cmd/tools/cli.version={{.Version}} -X github.com/kf5i/k3ai-core/cmd/tools/cli.commit={{.Commit}} -X github.com/kf5i/k3ai-core/cmd/tools/cli.goVersion={{.Env.GO_VERSION}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: "{{.Version}}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "README.md"
      - ".gitignore"
      - "^site:"
      - "^examples:"
      - Merge pull request
      - Merge branch
